import { IUltimateDB } from "./IUltimateDB"

export const ultimate1500: IUltimateDB = {
  prcode: 93417531,
  model: 'Bort Ultimate 1500',
  link: 'https://b2b.bort-global.com/product/izmelchitel_pischevyih_othodov_Bort_Ultimate_1500',
  image: 'https://bort-global.ru/photo/product/93417531',
  steps: 3,
  reverce: false,
  booster: false,
  soundProofing: 'частичная',
  power: 1125,
  volume: 2300,
  hull: 'Нержавеющая сталь',
  protectionSystem: true,
  speed: 1400,
  weight: 27,
  powerHP: 1.5,
  productivity: 8,
  diameter: '3 1/2 (90мм)',
  bottom: '1...14',
  noiseLevel: 60,
  autoPowerOff: false,
  cordLength: 2,
  silentOperation: true,
  size: '250х250х410',
  grindingMaterial: 'Нержавеющая сталь',
  quietStart: true,
  motorType: 'Бесщеточный',
  loadingMethod: 'непрерывный',
  dishwasherConnection: true,
  wirelessButton: true,
  control: 'Электронное',
  smoothStart: true,
  quantityService: '130-300',
  price: 144790
}