import { IUltimateDB } from "./IUltimateDB"

export const ultimate2000: IUltimateDB = {
  prcode: 93417524,
  model: 'Bort Ultimate 2000',
  link: 'https://b2b.bort-global.com/product/izmelchitel_pischevyih_othodov_Bort_Ultimate_2000',
  image: 'https://bort-global.ru/photo/product/93417524',
  steps: 3,
  reverce: false,
  booster: false,
  soundProofing: 'полная',
  power: 1470,
  volume: 2500,
  hull: 'Нержавеющая сталь',
  protectionSystem: true,
  speed: 1400,
  weight: 40,
  powerHP: 2,
  productivity: 9,
  diameter: '3 1/2 (90мм)',
  bottom: '1...14',
  noiseLevel: 60,
  autoPowerOff: false,
  cordLength: 2,
  silentOperation: true,
  size: '300х300х530',
  grindingMaterial: 'Нержавеющая сталь',
  quietStart: true,
  motorType: 'Бесщеточный',
  loadingMethod: 'непрерывный',
  dishwasherConnection: true,
  wirelessButton: false,
  control: 'пневматическое',
  smoothStart: true,
  quantityService: '170-350',
  price: 243190
}